<Project>
  <PropertyGroup>
    <IsTestProject Condition="$(MSBuildProjectName.EndsWith('Tests')) OR $(MSBuildProjectName.EndsWith('.Test'))">true</IsTestProject>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDocumentationFile Condition=" '$(IsTestProject)' != 'true' ">true</GenerateDocumentationFile>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>
  
  <PropertyGroup>
    <Version>6.0.0.0-develop</Version>
    <Copyright>Copyright © XBIM Ltd</Copyright>
    <Company>Xbim Ltd.</Company>
    <Authors>Steve Lockley, Martin Cerny and XBIMTeam Contributors</Authors>
    <Product>XBIM WindowsUI</Product>
    <PackageLicenseExpression>CDDL-1.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/xBimTeam/XbimWindowsUI</PackageProjectUrl>
    <PackageIcon>xbim-toolkit-icon.png</PackageIcon>
    <PackageReleaseNotes>
      Now built on XBIM v6 to support .net core (.net8) and IFC4x3 schema and geometries
    </PackageReleaseNotes>
    <PackageTags>BIM, IFC, IfcXml, IfcZip, Ifc4, COBie, BuildingSmart</PackageTags>
    <RepositoryUrl>https://github.com/xBimTeam/XbimWindowsUI/tree/master</RepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\XbimOpenSourceKeyFile.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
  </PropertyGroup>

</Project>