; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "XbimXplorer"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "S.R.Lockley"
!define PRODUCT_WEB_SITE "http://xbim.codeplex.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\XbimXplorer.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

SetCompressor lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "..\..\..\..\..\License.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\XbimXplorer.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "XplorerSetup.exe"
InstallDir "$PROGRAMFILES\XbimXplorer"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "..\..\bin\x86\Release\HelixToolkit.Wpf.dll"
  File "..\..\bin\x86\Release\ICSharpCode.SharpZipLib.dll"
  File "..\..\bin\x86\Release\log4net.dll"
  File "..\..\bin\x86\Release\PropertyTools.dll"
  File "..\..\bin\x86\Release\PropertyTools.Wpf.dll"
  File "..\..\bin\x86\Release\TKBO.dll"
  File "..\..\bin\x86\Release\TKBool.dll"
  File "..\..\bin\x86\Release\TKBRep.dll"
  File "..\..\bin\x86\Release\TKernel.dll"
  File "..\..\bin\x86\Release\TKFillet.dll"
  File "..\..\bin\x86\Release\TKG2d.dll"
  File "..\..\bin\x86\Release\TKG3d.dll"
  File "..\..\bin\x86\Release\TKGeomAlgo.dll"
  File "..\..\bin\x86\Release\TKGeomBase.dll"
  File "..\..\bin\x86\Release\TKMath.dll"
  File "..\..\bin\x86\Release\TKMesh.dll"
  File "..\..\bin\x86\Release\TKOffset.dll"
  File "..\..\bin\x86\Release\TKPrim.dll"
  File "..\..\bin\x86\Release\TKShHealing.dll"
  File "..\..\bin\x86\Release\TKTopAlgo.dll"
  File "..\..\bin\x86\Release\Xbim.Common.dll"
  File "..\..\bin\x86\Release\Xbim.Ifc.dll"
  File "..\..\bin\x86\Release\Xbim.Ifc.Extensions.dll"
  File "..\..\bin\x86\Release\Xbim.Ifc2x3.dll"
  File "..\..\bin\x86\Release\Xbim.IO.dll"
  File "..\..\bin\x86\Release\Xbim.ModelGeometry.dll"
  File "..\..\bin\x86\Release\Xbim.ModelGeometry.Scene.dll"
  File "..\..\bin\x86\Release\Xbim.Presentation.dll"
  File "..\..\bin\x86\Release\XbimXplorer.exe"
  CreateDirectory "$SMPROGRAMS\XbimXplorer"
  CreateShortCut "$SMPROGRAMS\XbimXplorer\XbimXplorer.lnk" "$INSTDIR\XbimXplorer.exe"
  CreateShortCut "$DESKTOP\XbimXplorer.lnk" "$INSTDIR\XbimXplorer.exe"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\XbimXplorer\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\XbimXplorer\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\XbimXplorer.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\XbimXplorer.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\XbimXplorer.exe"
  Delete "$INSTDIR\Xbim.Presentation.dll"
  Delete "$INSTDIR\Xbim.ModelGeometry.Scene.dll"
  Delete "$INSTDIR\Xbim.ModelGeometry.dll"
  Delete "$INSTDIR\Xbim.IO.dll"
  Delete "$INSTDIR\Xbim.Ifc2x3.dll"
  Delete "$INSTDIR\Xbim.Ifc.Extensions.dll"
  Delete "$INSTDIR\Xbim.Ifc.dll"
  Delete "$INSTDIR\Xbim.Common.dll"
  Delete "$INSTDIR\TKTopAlgo.dll"
  Delete "$INSTDIR\TKShHealing.dll"
  Delete "$INSTDIR\TKPrim.dll"
  Delete "$INSTDIR\TKOffset.dll"
  Delete "$INSTDIR\TKMesh.dll"
  Delete "$INSTDIR\TKMath.dll"
  Delete "$INSTDIR\TKGeomBase.dll"
  Delete "$INSTDIR\TKGeomAlgo.dll"
  Delete "$INSTDIR\TKG3d.dll"
  Delete "$INSTDIR\TKG2d.dll"
  Delete "$INSTDIR\TKFillet.dll"
  Delete "$INSTDIR\TKernel.dll"
  Delete "$INSTDIR\TKBRep.dll"
  Delete "$INSTDIR\TKBool.dll"
  Delete "$INSTDIR\TKBO.dll"
  Delete "$INSTDIR\PropertyTools.Wpf.dll"
  Delete "$INSTDIR\PropertyTools.dll"
  Delete "$INSTDIR\log4net.dll"
  Delete "$INSTDIR\ICSharpCode.SharpZipLib.dll"
  Delete "$INSTDIR\HelixToolkit.Wpf.dll"

  Delete "$SMPROGRAMS\XbimXplorer\Uninstall.lnk"
  Delete "$SMPROGRAMS\XbimXplorer\Website.lnk"
  Delete "$DESKTOP\XbimXplorer.lnk"
  Delete "$SMPROGRAMS\XbimXplorer\XbimXplorer.lnk"

  RMDir "$SMPROGRAMS\XbimXplorer"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd