<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
		<TargetFrameworks>net8.0-windows7.0</TargetFrameworks>
		<OutputType>WinExe</OutputType>	
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x86</Platforms>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Xbim.Presentation\Xbim.Presentation.csproj" />
	</ItemGroup>
</Project>